services:
  - type: web
    name: duelcade-game-server
    runtime: docker
    plan: free
    region: frankfurt
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
